"""Chae

Revision ID: a688f71d3511
Revises: b85e624fee1d
Create Date: 2020-06-02 22:08:02.274759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a688f71d3511'
down_revision = 'b85e624fee1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
